name: CI

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

permissions:
  contents: read

jobs:
  ci:
    uses: elixir-vibe/actions/.github/workflows/elixir-ci.yml@v1
    with:
      restore-plt-cache: false
      latest-command: rm -f _build/dev/dialyxir*.plt _build/test/dialyxir*.plt && mix ci
